import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { ArrowUpRight, ArrowRight, FileText, ScanLine, CheckCheck, Upload, ShieldCheck, AlertCircle, Loader2, Layers3 } from "lucide-react";
import { api, formatPercent } from "../lib/api";
import { displayFilename } from "../lib/labels";
import StatusBadge from "../components/StatusBadge";

export default function Dashboard() {
  const query = useQuery({queryKey: ["dashboard"], queryFn: api.dashboard, refetchInterval: 10000});
  if (query.isLoading) return <div className="app-shell flex items-center gap-3 py-24"><Loader2 className="h-5 w-5 animate-spin"/>Loading your workspace…</div>;
  if (query.isError) return <div className="app-shell"><div className="empty-state"><AlertCircle className="mb-4 h-8 w-8"/><h1 className="text-lg font-semibold">Workspace unavailable</h1><p className="mt-2 text-sm text-ink-muted">Check that the API is running, then try again.</p><button className="btn-primary mt-5" onClick={() => query.refetch()}>Try again</button></div></div>;
  const data = query.data!;
  const reviews = data.recent.filter(d => d.review_count > 0 || d.status === "error" || d.status === "partial");
  const stats = [
    {label: "Policy documents", value: data.total_documents, detail: `${data.extracted_policies} extracted`, icon: FileText},
    {label: "Fields extracted", value: data.fields_found ?? 0, detail: "Across your policy library", icon: Layers3},
    {label: "Fields to review", value: data.fields_requiring_review, detail: "Ambiguities and validation flags", icon: AlertCircle},
    {label: "Evidence coverage", value: formatPercent(data.evidence_coverage ?? 0), detail: "Cited claims passing source checks", icon: ShieldCheck},
  ];
  return <div className="app-shell space-y-7">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">YOUR WORKSPACE</div><h1 className="page-title mt-2">Policy overview</h1><p className="mt-2 text-sm text-ink-muted">A clear view of your documents, extracted terms, and review priorities.</p></div><Link to="/knowledge-base" className="btn-primary"><Upload className="h-4 w-4"/>Upload policy</Link></header>
    <section className="overview-hero">
      <div className="relative z-10 max-w-xl"><span className="inline-flex items-center gap-2 text-xs font-medium text-teal-200"><span className="h-1.5 w-1.5 rounded-full bg-teal-300"/>DOCUMENT INTELLIGENCE, WITH EVIDENCE</span><h2 className="mt-5 text-3xl font-semibold leading-tight tracking-tight sm:text-[38px]">From policy pages<br/>to clear answers.</h2><p className="mt-4 max-w-md text-sm leading-7 text-slate-300">Extract the details that matter. Trace every answer to its source. Bring structured policy data into your QMS.</p><Link to={data.recent[0] ? `/workspace?doc=${data.recent[0].id}` : "/knowledge-base"} className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-white">{data.extracted_policies ? "Explore an extraction" : "Add your first document"}<ArrowRight className="h-4 w-4"/></Link></div>
      <div className="hero-document" aria-hidden="true"><div className="flex items-center gap-3 border-b border-slate-100 pb-4"><div className="rounded-xl bg-teal-50 p-3 text-teal-700"><FileText className="h-6 w-6"/></div><div><div className="font-semibold text-slate-800">Policy intelligence</div><div className="mt-1 text-xs text-slate-400">Source → structured data</div></div></div><div className="space-y-4 py-5">{["Insurer & policy details", "Benefits & coverage limits", "Waiting periods & waivers"].map(x=><div className="flex items-center gap-3 text-xs text-slate-600" key={x}><CheckCheck className="h-4 w-4 text-teal-600"/>{x}</div>)}</div><div className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-[11px] text-slate-500"><span>Page-level citations</span><span className="font-mono text-teal-700">{'{ QMS JSON }'}</span></div></div>
    </section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Portfolio metrics">{stats.map(({label,value,detail,icon:Icon})=><article key={label} className="card p-5"><div className="flex items-center justify-between"><span className="text-xs font-medium text-ink-muted">{label}</span><Icon className="h-4 w-4 text-ink-faint"/></div><div className="mt-4 text-[32px] font-semibold leading-none tracking-tight tabular-nums">{value}</div><p className="mt-3 text-[11px] text-ink-muted">{detail}</p></article>)}</section>
    <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_300px]">
      <section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-border px-6 py-5"><div><h2 className="font-semibold">Policy library</h2><p className="mt-1 text-xs text-ink-muted">Your most recently added documents</p></div><Link className="flex items-center gap-1 text-xs font-semibold text-brand-700" to="/knowledge-base">View all<ArrowUpRight className="h-3.5 w-3.5"/></Link></div>
      {!data.recent.length ? <div className="m-5 empty-state"><FileText className="mb-3 h-8 w-8 text-ink-faint"/><p className="font-medium">Your library starts here</p><p className="mt-2 text-sm text-ink-muted">Upload a PDF to see its details and source evidence.</p><Link className="btn-secondary mt-5" to="/knowledge-base">Add a policy</Link></div> : <div className="divide-y divide-border">{data.recent.map(doc=><Link key={doc.id} to={`/workspace?doc=${doc.id}`} className="group flex items-center gap-4 px-6 py-5 transition-colors hover:bg-surface-muted/50"><div className="flex h-11 w-10 shrink-0 items-center justify-center rounded-lg border border-border bg-surface text-brand-700"><FileText className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-semibold group-hover:text-brand-700">{displayFilename(doc.filename)}</div><div className="mt-1 truncate text-xs text-ink-muted">{doc.insurer || "Identity pending"}<span className="mx-2">·</span>{doc.page_count} pages</div></div><div className="hidden text-right sm:block"><StatusBadge status={doc.status}/><p className="mt-1 text-[11px] text-ink-muted">{doc.fields_found} fields extracted</p></div><ArrowUpRight className="h-4 w-4 shrink-0 text-ink-faint group-hover:text-brand-700"/></Link>)}</div>}</section>
      <aside className="space-y-5"><div className="card p-5"><div className="flex items-center gap-2"><span className="rounded-md bg-amber-50 p-1.5 text-amber-700 dark:bg-amber-900/20"><AlertCircle className="h-4 w-4"/></span><h2 className="text-sm font-semibold">Review priorities</h2></div>{reviews.length ? <div className="mt-4 space-y-4">{reviews.slice(0,3).map(doc=><Link className="block rounded-lg border border-border p-3 hover:bg-surface-muted" key={doc.id} to={`/workspace?doc=${doc.id}`}><div className="truncate text-xs font-semibold">{displayFilename(doc.filename)}</div><div className="mt-1 text-xs text-ink-muted">{doc.status === "error" ? "Processing needs attention" : `${doc.review_count} fields flagged for review`}</div></Link>)}</div> : <p className="mt-4 text-sm leading-6 text-ink-muted">{data.extracted_policies ? "No validation flags in recent documents. Review source evidence before integrating answers." : "Validation flags will appear here after your first extraction."}</p>}</div>
      <div className="rounded-xl border border-brand-200/60 bg-brand-50/50 p-5 dark:border-brand-900 dark:bg-brand-950/30"><ScanLine className="h-5 w-5 text-brand-700"/><h3 className="mt-3 text-sm font-semibold">Know what the source says</h3><p className="mt-2 text-xs leading-6 text-ink-muted">Unknown means the system could not establish an answer. Confidence and evidence coverage are not accuracy scores.</p><Link className="mt-4 inline-flex items-center gap-2 text-xs font-semibold text-brand-700" to="/evidence">Inspect evidence<ArrowRight className="h-3.5 w-3.5"/></Link></div></aside>
    </div>
  </div>;
}
