from __future__ import annotations

from typing import Any, Protocol


class PolicyGraphStore(Protocol):
    async def upsert_policy(self, policy: Any) -> None: ...

    async def get_policy_graph(self, policy_id: str) -> dict: ...

    async def compare_policies(self, first_policy_id: str, second_policy_id: str) -> dict: ...

    async def delete_policy(self, policy_id: str) -> None: ...

    async def healthcheck(self) -> Any: ...
